# This file was generated by GoReleaser. DO NOT EDIT.
cask "tack" do
  version "0.1.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "0988abab160461fc31be5c42e481ce6eb17697dc8dbe9b50fcd8170e44f5e1a6"
      url "https://github.com/syndg/tack/releases/download/v0.1.0-alpha.1/tack_Darwin_x86_64.tar.gz",
        verified: "github.com/syndg/tack"
    end
    on_arm do
      sha256 "8b099e21bc3d18d2a84eb57ffa8f4e8b1415ac3f9bea833af788566dfade6d44"
      url "https://github.com/syndg/tack/releases/download/v0.1.0-alpha.1/tack_Darwin_arm64.tar.gz",
        verified: "github.com/syndg/tack"
    end
  end

  on_linux do
    on_intel do
      sha256 "a475df04afc8cca80b840088e6b046b80fc9448af3052df88573bbac83657629"
      url "https://github.com/syndg/tack/releases/download/v0.1.0-alpha.1/tack_Linux_x86_64.tar.gz",
        verified: "github.com/syndg/tack"
    end
    on_arm do
      sha256 "da00b10dbcf104dc1e067ec4a329159bc5207e76f0494c3dc8e2f19823dca387"
      url "https://github.com/syndg/tack/releases/download/v0.1.0-alpha.1/tack_Linux_arm64.tar.gz",
        verified: "github.com/syndg/tack"
    end
  end

  name "tack"
  desc "Deterministic harness for agentic code execution"
  homepage "https://github.com/syndg/tack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tack"]
    end
  end
end
